# k create ns teams
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain # Ill want to look into this more
allowVolumeExpansion: true
volumeBindingMode: Immediate

---
# I could just use local below instead of hostpath to make it work on cluster 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  namespace: teams
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: teams
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

