name: Manual Terraform Action

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (apply/destroy/plan)'
        required: true
        default: 'plan'
      num_of_instances:
        description: 'Number of instances'
        required: true
        default: '3'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Terraform AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        # You can use the TERRAFORM_PRIVATE_KEY directly in terraform commands or other places in the script as needed.

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        cd terraform
        TF_LOG=DEBUG terraform destroy -auto-approve \
        -var="instance_count=${{ github.event.inputs.num_of_instances }}" \
        -var="user_data_secret=${{ secrets.USER_DATA_SECRET }}" \
        -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
        -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
        -var="aws_region=us-west-1" # Change this to your desired region or use another secret/environment variable

        
    - name: Terraform Plan
      if: github.event.inputs.action == 'apply' || github.event.inputs.action == "plan"
      run: |
        cd terraform
        TF_LOG=DEBUG terraform plan \
        -var="instance_count=${{ github.event.inputs.num_of_instances }}" \
        -var="user_data_secret=${{ secrets.USER_DATA_SECRET }}" \
        -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
        -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
        -var="aws_region=us-west-1" # Change this to your desired region or use another secret/environment variable

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        cd terraform
        terraform apply -auto-approve \
        -var="instance_count=${{ github.event.inputs.num_of_instances }}" \
        -var="user_data_secret=${{ secrets.USER_DATA_SECRET }}" \
        -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
        -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
        -var="aws_region=us-west-1" # Change this to your desired region or use another secret/environment variable
